name: Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: Minimal Spyglass
      MODRINTH_ID: 9OteWkCS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Variables
        run: |
          set -euo pipefail
          echo "VERSION=${GITHUB_REF_NAME}" >> "$GITHUB_ENV"
          echo "VERSION_NO_V=${GITHUB_REF_NAME#v}" >> "$GITHUB_ENV"
          echo "RESOURCEPACK_FOLDER=${PROJECT_NAME}" >> "$GITHUB_ENV"
          echo "RESOURCEPACK_FILE=${PROJECT_NAME} ${GITHUB_REF_NAME}.zip" >> "$GITHUB_ENV"
          echo "RESOURCEPACK_FILE_NO_SPACES=${PROJECT_NAME// /-}-${GITHUB_REF_NAME}.zip" >> "$GITHUB_ENV"

      - name: Extract Changelog
        id: changelog
        run: |
          set -euo pipefail
          changelog=$(awk "/^## \[${VERSION//./\\.}\]/ {flag=1; next} /^## / {flag=0} flag" CHANGELOG.md)
          changelog="${changelog//'%'/'%25'}"
          echo "log<<EOF" >> "$GITHUB_OUTPUT"
          echo "${changelog}" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Zip Resource Pack
        working-directory: src/${{ env.RESOURCEPACK_FOLDER }}
        run: |
          set -euo pipefail
          zip -r "${{ env.RESOURCEPACK_FILE }}" ./*
          cp "${{ env.RESOURCEPACK_FILE }}" "${{ env.RESOURCEPACK_FILE_NO_SPACES }}"
          mv "${{ env.RESOURCEPACK_FILE }}" "$GITHUB_WORKSPACE/"
          mv "${{ env.RESOURCEPACK_FILE_NO_SPACES }}" "$GITHUB_WORKSPACE/"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.RESOURCEPACK_FILE_NO_SPACES }}
          body: ${{ steps.changelog.outputs.log }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Resource Pack
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          name: ${{ env.PROJECT_NAME }} ${{ env.VERSION }}
          version: ${{ env.VERSION_NO_V }}
          version-type: release
          game-version-filter: releases
          game-versions: |
            [1.17,]
          loaders: |
            resourcepack

          changelog: ${{ steps.changelog.outputs.log }}
          files: ${{ env.RESOURCEPACK_FILE }}
